asyncapi: 2.6.0
info:
  title: Client Inspection
  version: 2.9.1
  description: |
    This plugin provides information about clients connected to the broker.
    The topic of the plugins control API is `$CONTROL/cedalo/inspect/v1`.

    Currently supported commands offered by the API are `listClients` for an
    overview which clients are connected and the `getClient` command to get
    detailed information about a specific client.

defaultContentType: application/json
channels:
  $CONTROL/cedalo/inspect/v1:
    publish:
      message:
        $ref: '#/components/messages/ControlRequest'
  $CONTROL/cedalo/inspect/v1/response:
    subscribe:
      message:
        $ref: '#/components/messages/ControlResponse'
components:
  messages:
    ControlRequest:
      name: controlRequest
      title: Request to execute listClients/getClient
      payload:
        $ref: '#/components/schemas/controlRequestPayload'
      examples:
        - name: listClients
          summary: Example of an listClients message.
          payload:
            commands:
              - command: listClients
                verbose: true
                count: 10
                offset: 100
                correlationData: 12345-list-req
        - name: getClient
          summary: Example of an getClient message.
          payload:
            commands:
              - command: getClient
                clientid: monitoring-client
                correlationData: 12345-get-req

    ControlResponse:
      name: controlResponse
      title: Response to an executed listClients/getClient request
      payload:
        $ref: '#/components/schemas/controlResponsePayload'
      examples:
        - name: getClient
          summary: successful getClient response message.
          payload:
            responses:
              - command: getClient
                data:
                  clientid: admin-connect
                  username: admin
                  address: 127.0.0.1
                  protocol: MQTT
                  protocolVersion: v3.1.1
                  numSubscriptions: 1
                  numPublished: 2
                  numSubscribed: 1
                  numDropped: 0
                  bytesPublished: 50
                  bytesSubscribed: 125
                  connected: true
                  lastConnect: 1668005037000
                  lastDisconnect: null
                  keepalive: 60
                  cleanSession: false
                  tls:
                    clientCertificate: <cert in PEM format>
                    version: TLSv1.3
                    ciphers: TLS_AES_256_GCM_SHA384
                  listener:
                    port: 8883
                    bind_address: 127.0.0.1
                  will:
                    topic: last/will/topic
                    qos: 1
                    retain: true
                    payload: <base64 encoded payload>
                    properties:
                      - identifier: user-property
                        name: key
                        value: value
                      - identifier: content-type
                        value: application/test
                    delayInterval: 3
                  subscriptions:
                    - '$SYS/#'
                  queues:
                    bytesIn: 0
                    bytesOut: 0
                    bytesMax: 0
                    messagesIn: 0
                    messagesMax: 1000
                    messagesInQos12: 0
                    messagesOut: 0
                    messagesOutQos12: 0
                    pagedMessagesOut: 0
                    pagedMessagesMax: 20
                  inflight:
                    bytesIn: 0
                    bytesOut: 0
                    bytesMax: 0
                    messagesIn: 0
                    messagesInMax: 20
                    messagesOut: 0
                    messagesOutMax: 20
                    messagesMax: 20
                correlationData: 37a6e977-2b4f-4431-83f7-5bd93b35c152
        - name: listClients with `verbose=true`
          summary: successful listClients response message.
          payload:
            responses:
                - command: listClients
                  data:
                    clients:
                      - clientid: admin-connect
                        username: admin
                        address: 127.0.0.1
                        protocol: MQTT
                        protocolVersion: v3.1.1
                        connected: true
                        lastConnect: 1668005037000
                        lastDisconnect:
                        queues:
                          bytesOut: 0
                          bytesMax: 0
                          messagesOut: 0
                          messagesMax: 1000
                          pagedMessagesOut: 0
                          pagedMessagesMax: 1000
                      - clientid: auto-97E83DDF-6255-D78B-C776-4E02664C3E4C
                        username: demo
                        address: 127.0.0.1
                        protocol: MQTT
                        protocolVersion: v5
                        connected: false
                        lastConnect: 1668005032144
                        lastDisconnect: 1668005045311
                    totalCount: 2
                  correlationData: 37a6e977-2b4f-4431-83f7-5bd93b35c152
        - name: listClients with `verbose=false``
          payload:
            responses:
              - command: listClients
                correlationData: 37a6e977-2b4f-4431-83f7-5bd93b35c152
                data:
                  clients:
                  - admin-connect
                  - auto-97E83DDF-6255-D78B-C776-4E02664C3E4C
                  totalCount: 2
        - name: error
          summary: Example of an error response message.
          payload:
            responses:
              - command: getClient
                error: Client not found
                correlationData: 37a6e977-2b4f-4431-83f7-5bd93b35c152

  schemas:
    controlRequestPayload:
      type:
        - object
      properties:
        commands:
          type: array
          items:
            type:
              - object
            anyOf:
              - description: listClients request
                properties:
                  command:
                    type: string
                    enum:
                      - listClients
                    description: |
                      Command to request the plugin to return the list of
                      clients connected to the broker.
                  verbose:
                    type: boolean
                    default: false
                    description: |
                      If set to `false` only client-ids will be listed.
                  count:
                    type: integer
                    default: -1
                    description: |
                      Number of client entries which should be returned. Set `-1`
                      for all entries.
                  offset:
                    type: integer
                    default: 0
                    description: |
                      References a specific location in the list where start
                      returning values from. Set to `0` to start at the beginning.
                  correlationData:
                    $ref: '#/components/schemas/correlationData'
                additionalProperties: false
                required:
                  - command
              - description: getClients request
                properties:
                  command:
                    type: string
                    enum:
                      - getClient
                    description: |
                      Command to request the plugin to return detailed metrics of
                      a specific client connected to the broker.
                  clientid:
                    type: string
                    description: |
                      Identifier of the connected client, we want the metrics for.
                  correlationData:
                    $ref: '#/components/schemas/correlationData'
                additionalProperties: false
                required:
                  - command
                  - clientid
      additionalProperties: false
    controlResponsePayload:
      type:
        - object
      properties:
        responses:
          type: array
          items:
            type:
              - object
            anyOf:
              - description: listClients response
                properties:
                  command:
                    type: string
                    enum:
                      - listClients
                    description: >-
                      Command which describes the action processed by the plugin.
                  data:
                    type: object
                    description: Specified if request has been processed successfully
                    properties:
                      clients:
                        properties:
                          username:
                            type: string
                            description: Username used for authentication, otherwise <anonymous>. [free]
                          clientid:
                            type: string
                            description: Textual identifier of the client. [free]
                          address:
                            type: string
                            description: IP address of the client as a string. [free]
                          protocol:
                            type: string
                            enum:
                              - MQTT
                              - MQTT-SN
                              - MQTT-WS
                            description: Protocol used to connect to the broker. [free]
                          protocolVersion:
                            type: string
                            enum:
                              - v3.1
                              - v3.1.1
                              - v5
                            description: MQTT protocol version used by the client. [free]
                          connected:
                            type: boolean
                            description:
                              Boolean flag which describes if a client is currently connected
                              to the broker. [premium]
                          lastConnect:
                            type: integer
                            description: |
                              Epoch in milliseconds when the client connected to broker. [premium]
                          lastDisconnect:
                            type: integer
                            description: |
                              Epoch in milliseconds when the client disconnected from broker.
                              `null` if never disconnected before. [premium]
                          queues:
                            type: object
                            description: |
                              Metrics helping to analyze the current load on the message queues
                              of the broker for this client. [premium]
                            properties:
                              bytesOut:
                                type: integer
                                description: Outgoing queued message bytes. [premium]
                              bytesMax:
                                type: integer
                                description: Maximum bytes queued. [premium]
                              messagesOut:
                                type: integer
                                description: Outgoing queued message count. [premium]
                              messagesMax:
                                type: integer
                                description: Queued message count upper limit. [premium]
                              pagedMessagesOut:
                                type: integer
                                description: Outgoing queued messages paged to disk count. [premium]
                              pagedMessagesMax:
                                type: integer
                                description: Outgoing queued messages paged to disk upper count limit. [premium]
                            additionalProperties: false
                      totalCount:
                        type: integer
                        description: Result count
                    additionalProperties: false
                    required:
                      - clients
                      - totalCount
                  correlationData:
                    $ref: '#/components/schemas/correlationData'
                additionalProperties: false
                required:
                  - command
                  - data
              - description: getClient response
                properties:
                  command:
                    type: string
                    enum:
                      - getClient
                    description: >-
                      Command which describes the action processed by the plugin.
                  data:
                    type: object
                    description: Specified if request has been processed successfully
                    properties:
                      username:
                        type: string
                        description: Username used for authentication, otherwise `<anonymous>`. [free]
                      clientid:
                        type: string
                        description: Textual identifier of the client. [free]
                      address:
                        type: string
                        description: IP address of the client as a string. [free]
                      protocol:
                        type: string
                        enum:
                          - MQTT
                          - MQTT-SN
                          - MQTT-WS
                        description: Protocol used to connect to the broker. [free]
                      protocolVersion:
                        type: string
                        enum:
                          - v3.1
                          - v3.1.1
                          - v5
                        description: MQTT protocol version used by the client. [free]
                      numSubscriptions:
                        type: integer
                        description: Number of subscriptions currently active for this client. [premium]
                      numPublished:
                        type: integer
                        description: Number of published messages received from this client. [premium]
                      numSubscribed:
                        type: integer
                        description: Number of published messages sent to this client. [premium]
                      numDropped:
                        type: integer
                        description: Number of messages dropped due to queue limit for this client. [premium]
                      bytesPublished:
                        type: integer
                        description: Number of bytes in published message payloads received from this client. [premium]
                      bytesSubscribed:
                        type: integer
                        description: Number of bytes in published message payloads sent to this client. [premium]
                      connected:
                        type: boolean
                        description: Boolean flag which describes if a client is currently connected to the broker [premium]
                      lastConnect:
                        type: integer
                        description: Epoch in milliseconds when the client connected to broker [premium]
                      lastDisconnect:
                        type:
                          - integer
                          - "null"
                        description: Epoch in milliseconds when the client disconnected from broker. `null` if never disconnected before. [premium]
                      keepalive:
                        type: integer
                        description: Keep alive in seconds configured for this client [premium]
                      cleanSession:
                       type: boolean
                       description: Set to `true` if the broker will reset the session, when the client reconnects. [premium]
                      tls:
                        type: object
                        description: Encryption details, if the client used certificates for connecting. [premium]
                        properties:
                          clientCertificate:
                            type: string
                            description: Client certificate in PEM format. [premium]
                          version:
                            type: string
                            description: SSL/TLS version used
                            example: TLSv1.3
                          ciphers:
                            type: string
                            description: TLS ciphers used for the secure connection.
                            example: TLS_AES_256_GCM_SHA384
                      listener:
                        type: object
                        description: Details about the brokers listener the client connected to. [premium]
                        properties:
                          port:
                            type: integer
                            description: Port of the brokers listener, the client is connected to. [premium]
                          bind_address:
                            type: string
                            description: If specified, the listeners IP address it is bound to. [premium]
                            example: 127.0.0.1
                      will:
                        type: object
                        description: Details about the last will message if set during the connect request. [premium]
                        properties:
                          topic:
                            type: string
                            description: Topic where the last will message will be published on. [premium]
                          qos:
                            type: integer
                            description: QOS of the publish. [premium]
                          retain:
                            type: boolean
                            description: Boolean retained message flag. [premium]
                          payload:
                            type: string
                            description: Base64 encoded message payload. [premium]
                          properties:
                            type: array
                            description:  MQTT5 properties of the message. [premium]
                            items:
                              type: object
                              properties:
                                identifier:
                                  type: string
                                name:
                                  type: string
                                value:
                                  type: string
                              require:
                                - identifier
                                - value
                          delayInterval:
                            type: integer
                            description: Delay before publishing the message. [premium]
                      subscriptions:
                        type: array
                        description: List of topic filter (may include `#` wildcards) a client subscribed to. [premium]
                        items:
                          type: string
                      queues:
                        type: object
                        description: Metrics helping to analyze the current load on the message queues of the broker for this client [premium]
                        properties:
                          bytesIn:
                            type: integer
                            description: Incoming queued message bytes. [premium]
                          bytesOut:
                            type: integer
                            description: Outgoing queued message bytes. [premium]
                          bytesMax:
                            type: integer
                            description: Maximum bytes queued. [premium]
                          messagesIn:
                            type: integer
                            description: Incoming queued message count. [premium]
                          messagesMax:
                            type: integer
                            description: Queued message count upper limit. [premium]
                          messagesInQos12:
                            type: integer
                            description: Incoming queued messages with QOS 1 or 2. [premium]
                          messagesOut:
                            type: integer
                            description: Outgoing queued message count. [premium]
                          messagesOutQos12:
                            type: integer
                            description: Outgoing queued messages with QOS 1 or 2. [premium]
                          pagedMessagesOut:
                            type: integer
                            description: Outgoing queued messages paged to disk count. [premium]
                          pagedMessagesMax:
                            type: integer
                            description: Outgoing queued messages paged to disk count upper limit. [premium]
                      inflight:
                        type: object
                        description: Metrics helping to analyze the current load on the messages currently processed by the broker for this client [premium]
                        properties:
                          bytesIn:
                            type: integer
                            description: Incoming inflight message bytes. [premium]
                          bytesOut:
                            type: integer
                            description: Outgoing inflight message bytes. [premium]
                          bytesMax:
                            type: integer
                            description: Inflight message bytes upper limit. [premium]
                          messagesIn:
                            type: integer
                            description: Incoming inflight message count. [premium]
                          messagesInMax:
                            type: integer
                            description: Limit for number of incoming inflight messages. [premium]
                          messagesOut:
                            type: integer
                            description: Outgoing inflight message count. [premium]
                          messagesOutMax:
                            type: integer
                            description: Limit for number of outgoing inflight messages. [premium]
                          messagesMax:
                            type: integer
                            description: Inflight message count upper limit. [premium]
                  correlationData:
                    $ref: '#/components/schemas/correlationData'
                additionalProperties: false
                required:
                  - command
                  - data
              - description: error response
                properties:
                  command:
                    type: string
                    enum:
                      - listClients
                      - getClient
                    description: >-
                      Command which describes the action processed by the plugin.
                  error:
                    type: string
                    examples:
                      - Client not found
                  correlationData:
                    $ref: '#/components/schemas/correlationData'
                additionalProperties: false
                required:
                  - command
                  - error
      additionalProperties: false
    correlationData:
      type: string
      description: |
        This is an optional value to be able to identify the relation
        between request and response. The plugin will add the provided
        value in the response message.
      examples:
        - 37a6e977-2b4f-4431-83f7-5bd93b35c152
