asyncapi: 2.6.0
info:
  title: Client Control
  version: 2.9.1
  description: |
    The client control API gives the user the ability to apply different commands
    to connected clients (e.g. disconnect a client). These commands can be requested
    via the plugins control API. A controlling client can publish requests to
    `$CONTROL/cedalo/client-control/v1` and the related response message will be published
    by the plugin on `$CONTROL/cedalo/client-control/v1/response`.

    ***Note:*** Using this plugin requires a *valid license*. All commands will
    return an error if it is expired or could not be read.

defaultContentType: application/json
channels:
  $CONTROL/cedalo/client-control/v1:
    publish:
      message:
        $ref: '#/components/messages/ControlRequest'
  $CONTROL/cedalo/client-control/v1/response:
    subscribe:
      message:
        $ref: '#/components/messages/ControlResponse'
components:
  messages:
    ControlRequest:
      name: controlRequest
      title: Request to apply a client action
      payload:
        $ref: '#/components/schemas/controlRequestPayload'
      examples:
        - name: disconnectClient
          summary: Example of an disconnectClient request.
          payload:
            commands:
              - command: disconnectClient
                clientid: my-client
                correlationData: 716cc776-d044-4772-b991-d9b55e2e034c
        - name: subscribeClient
          summary: Examples of an subscribeClient request.
          payload:
            commands:
              - command: subscribeClient
                clientid: my-client
                topic: '/sensors/1/#'
                qos: 0
                options:
                  no_local: false
                  retain_as_published: false
                  send_retain: always
                correlationData: 37a6e977-2b4f-4431-83f7-5bd93b35c152
        - name: unsubscribeClient
          payload:
            commands:
              - command: unsubscribeClient
                clientid: my-client
                topic: "/sensors/1/#"
                correlationData: 37a6e977-2b4f-4431-83f7-5bd93b35c152


    ControlResponse:
      name: controlResponse
      title: Response to an executed client action request
      payload:
        $ref: '#/components/schemas/controlResponsePayload'
      examples:
        - name: disconnectClient
          payload:
            responses:
              - command: disconnectClient
                data: {}
                correlationData: 716cc776-d044-4772-b991-d9b55e2e034c
        - name: subscribeClient
          payload:
            responses:
              - command: subscribeClient
                data: {}
                correlationData: 716cc776-d044-4772-b991-d9b55e2e034c
        - name: unsubscribeClient
          payload:
            responses:
              - command: unsubscribeClient
                data: {}
                correlationData: 716cc776-d044-4772-b991-d9b55e2e034c
        - name: error
          summary: Example of an error response message.
          payload:
            responses:
              - command: disconnectClient
                error: Client not found
                correlationData: 716cc776-d044-4772-b991-d9b55e2e034c

  schemas:
    controlRequestPayload:
      type:
        - object
      properties:
        commands:
          type: array
          items:
            type:
              - object
            anyOf:
              - description: disconnectClient request
                properties:
                  command:
                    type: string
                    enum:
                      - disconnectClient
                    description: |
                      Disconnects a client from the broker by `clientid`.
                  clientid:
                    type: string
                    description: |
                      Identifier of the connected client, we want to disconnect.
                  correlationData:
                    $ref: '#/components/schemas/correlationData'
                additionalProperties: false
                required:
                  - command
                  - clientid
              - description: subscribeClient request
                properties:
                  command:
                    type: string
                    enum:
                      - subscribeClient
                    description: |
                      Adds a subscription to a client for a specific topic.
                      This client then just needs to read the publish messages provided
                      by the broker.
                  clientid:
                    type: string
                    description: |
                      Textual identifier of the client, which should be subscribed to
                      the topic.
                  topic:
                    type: string
                    description: |
                      Topic filter the client should be subscribed to.
                  qos:
                    type: integer
                    description: |
                      Quality Of Service level requested for this subscription.
                  subscription_identifier:
                    type: integer
                    description: |
                      _Optional_ MQTTv5 parameter which can be set to identify packages
                      related to that subscription for example in the PUBLISH message
                      for the created subscription.
                  options:
                    type: object
                    description: |
                      MQTTv5 specific subscription options. Will be ignored for older
                      MQTT versions.
                    properties:
                      no_local:
                        type: boolean
                        description: |
                          If set to `true` the client will not receive messages he
                          published by himself.
                      retain_as_published:
                        type: boolean
                        description: |
                          If set to `true` the retain flag on an incoming message will
                          be exactly as set by the publishing client, rather than
                          indicating whether the message is fresh/stale.
                      send_retain:
                        type: string
                        enum:
                          - always
                          - new
                          - never
                          - "null"
                        default: "null"
                        description: |
                          If set to `always` and a client subscribes the broker will
                          always respond with the retain message. If set to `new` and
                          a client subscribes the broker will respond with the retain
                          message if the subscription is new. If set to `never` and a
                          client subscribes the broker will never respond with the
                          retain message.

                  correlationData:
                    $ref: '#/components/schemas/correlationData'
                additionalProperties: false
                required:
                  - command
                  - clientid
                  - topic
                  - qos
              - description: unsubscribeClient request
                properties:
                  command:
                    type: string
                    enum:
                      - unsubscribeClient
                    description: |
                      Removes a subscription from a client for a specific topic.
                      This client then does not receive any published messages provided
                      by the broker.
                  clientid:
                    type: string
                    description: |
                      Textual identifier of the client, which should be unsubscribed from
                      the topic.
                  topic:
                    type: string
                    description: |
                      Topic filter the client should be unsubscribed from.
                  correlationData:
                    $ref: '#/components/schemas/correlationData'
                additionalProperties: false
                required:
                  - command
                  - clientid
                  - topic
      additionalProperties: false
    controlResponsePayload:
      type:
        - object
      properties:
        responses:
          type: array
          items:
            type:
              - object
            anyOf:
              - description: disconnectClient response
                properties:
                  command:
                    type: string
                    enum:
                      - disconnectClient
                      - subscribeClient
                      - unsubscribeClient
                    description: >-
                      Command which describes the action processed by the plugin.
                  data:
                    type: object
                    description: Specified if request has been processed successfully
                  correlationData:
                    $ref: '#/components/schemas/correlationData'
                additionalProperties: false
                required:
                  - command
                  - data
              - description: error response
                properties:
                  command:
                    type: string
                    enum:
                      - disconnectClient
                    description: >-
                      Command which describes the action processed by the plugin.
                  error:
                    type: string
                    examples:
                      - Client not found
                  correlationData:
                    $ref: '#/components/schemas/correlationData'
                additionalProperties: false
                required:
                  - command
                  - error
      additionalProperties: false
    correlationData:
      type: string
      description: |
        This is an optional value to be able to identify the relation
        between request and response. The plugin will add the provided
        value in the response message.
      examples:
        - 716cc776-d044-4772-b991-d9b55e2e034c
